# Default values for ckan-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ckan:
  replicaCount: 1
  image:
    repository: ghcr.io/mosoriob/ckan
    tag: 1363a5f2796c2b5d2f88e1bc6f078317d3a2da70

  ckan:
    siteUrl: 'http://ckan.tacc.cloud'
    ckanPlugins: 'envvars activity image_view datatables_view datastore datapusher recline_view oauth2'
    extraEnv:
      - name: CKAN_OAUTH2_REGISTER_URL
        value: 'https://portals.tapis.io/auth/sign-up'
      - name: CKAN_OAUTH2_RESET_URL
        value: 'https://portals.tapis.io/auth/password/new'
      - name: CKAN_OAUTH2_EDIT_URL
        value: 'https://portals.tapis.io/auth/settings'
      - name: CKAN_OAUTH2_AUTHORIZATION_ENDPOINT
        value: 'https://portals.tapis.io/v3/oauth2/authorize'
      - name: CKAN_OAUTH2_TOKEN_ENDPOINT
        value: 'https://portals.tapis.io/v3/oauth2/tokens'
      - name: CKAN_OAUTH2_PROFILE_API_URL
        value: 'https://portals.tapis.io/v3/oauth2/profile'
      - name: CKAN_OAUTH2_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: ckan-oauth-secrets
            key: client-id
      - name: CKAN_OAUTH2_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: ckan-oauth-secrets
            key: client-secret
      - name: CKAN_OAUTH2_SCOPE
        value: 'openid profile email'
      - name: CKAN_OAUTH2_REMEMBERER_NAME
        value: 'auth_tkt'
      - name: CKAN_OAUTH2_PROFILE_API_USER_FIELD
        value: 'tapis/username'
      - name: CKAN_OAUTH2_PROFILE_API_FULLNAME_FIELD
        value: 'tapis/fullname'
      - name: CKAN_OAUTH2_PROFILE_API_MAIL_FIELD
        value: 'tapis/email'
      - name: CKAN_OAUTH2_AUTHORIZATION_HEADER
        value: 'Bearer'
      - name: CKAN_OAUTH2_JWT_ENABLE
        value: 'true'
      - name: CKANEXT__S3FILESTORE__HOST_NAME
        value: 'https://s3.mint.isi.edu'
      - name: CKANEXT__S3FILESTORE__CHECK_ACCESS_ON_STARTUP
        value: 'true'
      - name: CKANEXT__S3FILESTORE__AWS_BUCKET_NAME
        value: 'ckan'
      - name: CKANEXT__S3FILESTORE__REGION_NAME
        value: 'us-west-2'
      - name: CKANEXT__S3FILESTORE__SIGNATURE_VERSION
        value: 's3v4'
      - name: CKANEXT__S3FILESTORE__AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: ckan-s3-secrets
            key: aws-access-key-id
      - name: CKANEXT__S3FILESTORE__AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: ckan-s3-secrets
            key: aws-secret-access-key

  pvc:
    size: '1Gi'
    storageClassName: 'microk8s-hostpath'
    accessmode: 'ReadWriteOnce'

  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: ckan.tacc.cloud
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  solr:
    # Please see all available overrides at https://github.com/bitnami/charts/tree/master/bitnami/solr/#installing-the-chart
    # solr.enabled -- Flag to control whether to deploy SOLR
    enabled: true
    # Reduce replica count to 1
    replicaCount: 1
    # Configure cloud settings
    cloudEnabled: true
    cloudBootstrap: true
    collection: ckan
    # Single node configuration
    collectionShards: 1
    collectionReplicas: 1
    # Configure ZooKeeper settings
    zookeeper:
      enabled: true
      replicaCount: 1
    global:
      imageRegistry: ''
      imagePullSecrets: []
      storageClass: 'microk8s-hostpath'
