# Default values for ckan-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ckan:
  replicaCount: 1
  image:
    #repository: ghcr.io/mosoriob/ckan-tacc-images
    #tag: main
    repository: ghcr.io/mosoriob/ckan
    tag: 2.9.11
  ckanPlugins: 'envvars activity image_view datatables_view datastore datapusher recline_view'

  pvc:
    size: '1Gi'
    storageClassName: 'microk8s-hostpath'
    accessmode: 'ReadWriteOnce'

  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: ckan.tacc.cloud
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  solr:
    # Please see all available overrides at https://github.com/bitnami/charts/tree/master/bitnami/solr/#installing-the-chart
    # solr.enabled -- Flag to control whether to deploy SOLR
    enabled: true
    # Reduce replica count to 1
    replicaCount: 1
    # Configure cloud settings
    cloudEnabled: true
    cloudBootstrap: true
    collection: ckan
    # Single node configuration
    collectionShards: 1
    collectionReplicas: 1
    # Configure ZooKeeper settings
    zookeeper:
      enabled: true
      replicaCount: 1
    global:
      imageRegistry: ''
      imagePullSecrets: []
      storageClass: 'microk8s-hostpath'
